### ISSUE TITLE
Pipenv + Cement Issue

### ISSUE THREAD

**Issue by derks** [gatewaynode/smurf#38]
When you have a moment, would you mind submitting an issue on [datafolklabs/cement](https://github.com/datafolklabs/cement) regarding the trouble with Pipenv you mentioned in the README? I'm not familiar with what you're referring to, but would love to work it out if there are compatibility issues.

Thanks!

**Comment by gatewaynode** [comment]
Sure, I'll try to get to it tonight.  I'll need to recreate it to give you the correct details as I moved on pretty quickly.  Also, this might be a philosophical issue with Pipenv, possibly something not worth spending too much time on.  Thanks for checking in on it, I love your framework.

**Comment by gatewaynode** [comment]
Created https://github.com/datafolklabs/cement/issues/549
